mysql: &MYSQL
  dsn: "root:mysql-db@tcp(mysql:3306)/social_media_app_db?charset=utf8mb4&parseTime=True&loc=Local"
  defaultStringSize: 256
  disableDatetimePrecision: True
  dontSupportRenameIndex: True
  skipInitializeWithVersion: False

redis: &REDIS
  addr: redis:6379
  password: ""
  db: 0

minio: &MINIO
  endpoint: "minio:9000"
  access_key: minio
  secret_key: miniostorage
  bucket_name: media_storage
  use_ssl: false

kafka: &KAFKA
  brokers: ["kafka:9092"]
  topic: newsfeed
  zookeeper_connect: zookeeper:2181

authen_and_post_config:
  port: 8001
  mysql: *MYSQL
  redis: *REDIS
  minio: *MINIO

newsfeed_config:
  port: 8002
  mysql: *MYSQL
  redis: *REDIS
  minio: *MINIO
  kafka: *KAFKA

webapp_config:
  port: 8000
  nginx_host: "nginx:80"
  authen_and_post:
    hosts: ["aap:8001"]
  newsfeed:
    hosts: ["nfs:8002"]
