version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: cmd/web_app/Dockerfile
      target: test_env
    image: web_app
    ports:
      - 8000:8000
    depends_on:
      - authen_and_post
      - newsfeed
    networks:
      - intranet
      - default
    hostname: webapp

  authen_and_post:
    build:
      context: .
      dockerfile: cmd/authen_and_post_service/Dockerfile
      target: test_env
    image: authen_and_post_service
    ports:
      - 8001:8001
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - intranet
    hostname: aap

  newsfeed:
    build:
      context: .
      dockerfile: cmd/newsfeed_service/Dockerfile
      target: test_env
    image: newsfeed_service
    ports:
      - 8002:8002
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - intranet
    hostname: nfs

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql-db
      MYSQL_DATABASE: social_media_app_db
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - intranet
    hostname: mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - intranet
    hostname: redis

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    ports:
      - 9000:9000
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      timeout: 20s
      retries: 10
    networks:
      - intranet
    hostname: minio

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - intranet
    hostname: kafka

  zookeeper:
    image: confluentinc/cp-kafka:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # ports:
    #   - "2181:2181"
    networks:
      - intranet
    hostname: zookeeper

volumes:
  mysql_data:
  minio_data:

networks:
  intranet: {}
  default: {}
