version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - authen_and_post_1
      - authen_and_post_2
      - newsfeed_1
      - newsfeed_2
    networks:
      - intranet
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: cmd/web_app/Dockerfile
      target: test_env
    image: web_app
    ports:
      - "8000:8000"
    depends_on:
      - authen_and_post_1
      - authen_and_post_2
      - newsfeed_1
      - newsfeed_2
    networks:
      - intranet
    hostname: webapp

  authen_and_post_1:
    build:
      context: .
      dockerfile: cmd/authen_and_post_service/Dockerfile
      target: test_env
    image: authen_and_post_service
    ports:
      - "8001:8001"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - intranet
    hostname: aap-1

  authen_and_post_2:
    build:
      context: .
      dockerfile: cmd/authen_and_post_service/Dockerfile
      target: test_env
    image: authen_and_post_service
    ports:
      - "8003:8001"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - intranet
    hostname: aap-2

  newsfeed_1:
    build:
      context: .
      dockerfile: cmd/newsfeed_service/Dockerfile
      target: test_env
    image: newsfeed_service
    ports:
      - "8002:8002"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - intranet
    hostname: nfs-1

  newsfeed_2:
    build:
      context: .
      dockerfile: cmd/newsfeed_service/Dockerfile
      target: test_env
    image: newsfeed_service
    ports:
      - "8004:8002"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - intranet
    hostname: nfs-2

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql-db
      MYSQL_DATABASE: social_media_app_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - intranet
    hostname: mysql
    restart: always

  redis:
    image: redis:latest
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 3
    networks:
      - intranet
    hostname: redis
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      timeout: 20s
      retries: 10
    networks:
      - intranet
    hostname: minio
    restart: always

  create_minio_bucket:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 60;
      /usr/bin/mc alias set myminio http://minio:9000 minio miniostorage;
      if /usr/bin/mc ls myminio/social-media-bucket > /dev/null 2>&1; then
        echo 'Bucket already exists, skipping creation.';
      else
        /usr/bin/mc mb myminio/social-media-bucket;
        /usr/bin/mc policy set public myminio/social-media-bucket;
      fi;
      exit 0;"
    networks:
      - intranet

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "kafka-topics", "--list", "--bootstrap-server", "kafka:9092"]
      timeout: 20s
      retries: 10
    networks:
      - intranet
    hostname: kafka
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      timeout: 10s
      retries: 5
    networks:
      - intranet
    hostname: zookeeper
    restart: always

volumes:
  mysql_data:
  minio_data:

networks:
  intranet: {}
