global:
  scrape_interval: 5s # Prometheus scrapes the data every 5 seconds

scrape_configs:
  - job_name: "newsfeed" # The name of this job
    static_configs:
      - targets: ["host.docker.internal:8080"] # Points to the app on localhost
