// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: internal/grpc/newsfeed.proto

package newsfeed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNewsfeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsfeedRequest) Reset() {
	*x = GetNewsfeedRequest{}
	mi := &file_internal_grpc_newsfeed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsfeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsfeedRequest) ProtoMessage() {}

func (x *GetNewsfeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_newsfeed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsfeedRequest.ProtoReflect.Descriptor instead.
func (*GetNewsfeedRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_newsfeed_proto_rawDescGZIP(), []int{0}
}

func (x *GetNewsfeedRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetNewsfeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []uint64               `protobuf:"varint,1,rep,packed,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsfeedResponse) Reset() {
	*x = GetNewsfeedResponse{}
	mi := &file_internal_grpc_newsfeed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsfeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsfeedResponse) ProtoMessage() {}

func (x *GetNewsfeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_newsfeed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsfeedResponse.ProtoReflect.Descriptor instead.
func (*GetNewsfeedResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_newsfeed_proto_rawDescGZIP(), []int{1}
}

func (x *GetNewsfeedResponse) GetPostIds() []uint64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

var File_internal_grpc_newsfeed_proto protoreflect.FileDescriptor

var file_internal_grpc_newsfeed_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x30, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x73, 0x32, 0x66, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x12, 0x5a, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x12, 0x24, 0x2e, 0x6e,
	0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6e,
	0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_grpc_newsfeed_proto_rawDescOnce sync.Once
	file_internal_grpc_newsfeed_proto_rawDescData []byte
)

func file_internal_grpc_newsfeed_proto_rawDescGZIP() []byte {
	file_internal_grpc_newsfeed_proto_rawDescOnce.Do(func() {
		file_internal_grpc_newsfeed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_newsfeed_proto_rawDesc), len(file_internal_grpc_newsfeed_proto_rawDesc)))
	})
	return file_internal_grpc_newsfeed_proto_rawDescData
}

var file_internal_grpc_newsfeed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_newsfeed_proto_goTypes = []any{
	(*GetNewsfeedRequest)(nil),  // 0: newsfeed_service.GetNewsfeedRequest
	(*GetNewsfeedResponse)(nil), // 1: newsfeed_service.GetNewsfeedResponse
}
var file_internal_grpc_newsfeed_proto_depIdxs = []int32{
	0, // 0: newsfeed_service.Newsfeed.GetNewsfeed:input_type -> newsfeed_service.GetNewsfeedRequest
	1, // 1: newsfeed_service.Newsfeed.GetNewsfeed:output_type -> newsfeed_service.GetNewsfeedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_newsfeed_proto_init() }
func file_internal_grpc_newsfeed_proto_init() {
	if File_internal_grpc_newsfeed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_newsfeed_proto_rawDesc), len(file_internal_grpc_newsfeed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_newsfeed_proto_goTypes,
		DependencyIndexes: file_internal_grpc_newsfeed_proto_depIdxs,
		MessageInfos:      file_internal_grpc_newsfeed_proto_msgTypes,
	}.Build()
	File_internal_grpc_newsfeed_proto = out.File
	file_internal_grpc_newsfeed_proto_goTypes = nil
	file_internal_grpc_newsfeed_proto_depIdxs = nil
}
